### ISSUE TITLE
Fix this please!!

### ISSUE THREAD

**Issue by 20161302animesh** [kaushalvivek/Music-Downloader#5]
Any way you could help me fix this?
FFMPEG installed is the latest available version. OS: Ubuntu 16.04
Enter any Song's Name to Download it:
Believer
[youtube] 7wtfhZwyrcc: Downloading webpage
[youtube] 7wtfhZwyrcc: Downloading video info webpage
[youtube] 7wtfhZwyrcc: Extracting video information
WARNING: unable to extract uploader nickname
ERROR: Signature extraction failed: Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
video_id, player_url, s
File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 797, in _extract_signature_function
raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'/yts/jsbin/player-vflcNAJUd/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
(caused by ExtractorError(u"Cannot identify player u'/yts/jsbin/player-vflcNAJUd/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see https://yt-dl.org/update on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
mv: cannot stat '*.mp3': No such file or directory

**Comment by kaushalvivek** [comment]
Are you still facing this issue?
